name = "Hacka"
license = "The Unlicense"
licenselink = "https://github.com/tasten/hacka/blob/master/LICENSE"
description = "Minimal blog theme for Hackers"
homepage = "https://github.com/tasuten/hacka"
tags = ["blog", "minimal", "highlight.js"]
features = ["blog"]
min_version = "0.21"

[author]
  name = "TASUTEN"
  homepage = "https://tasuten.github.io/"

